const C=window.TGM_CONFIG||{};if(!C.SUPABASE_URL||!C.SUPABASE_PUBLISHABLE_KEY||C.SUPABASE_PUBLISHABLE_KEY.includes("PASTE_")){document.body.innerHTML="<h2 style='padding:30px'>Please create config.js from config.example.js and enter your Supabase publishable key.</h2>";throw Error("config")};const db=supabase.createClient(C.SUPABASE_URL,C.SUPABASE_PUBLISHABLE_KEY);let S={u:null,c:null,a:[],p:[],ct:[]},mode="login";const $=x=>document.getElementById(x),esc=x=>String(x??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));const money=x=>(S.c?.currency||"PKR")+" "+Number(x||0).toLocaleString(undefined,{minimumFractionDigits:2});function msg(x){$("msg").textContent=x||""}
$("loginTab").onclick=()=>{mode="login";$(".signup")?.classList.add("hide");document.querySelector(".signup").style.display="none";$("loginTab").style.background="#172033";$("signupTab").style.background="#eef2f6"};$("signupTab").onclick=()=>{mode="signup";document.querySelector(".signup").style.display="block";$("signupTab").style.background="#172033";$("loginTab").style.background="#eef2f6"};
$("authForm").onsubmit=async e=>{e.preventDefault();msg("Please wait...");let r=mode==="signup"?await db.auth.signUp({email:$("email").value,password:$("pass").value,options:{data:{full_name:$("name").value}}}):await db.auth.signInWithPassword({email:$("email").value,password:$("pass").value});if(r.error)msg(r.error.message);else if(mode==="signup"&&!r.data.session)msg("Account created. Check your email, then login.");else msg("")};
$("logout").onclick=()=>db.auth.signOut();document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>show(b.dataset.p));function show(p){document.querySelectorAll("main section").forEach(s=>s.classList.add("hide"));$(p).classList.remove("hide");if(p==="reports")report()}
async function enter(u){S.u=u;$("auth").classList.add("hide");$("app").classList.remove("hide");$("who").textContent=u.email;await profile();await load()}
async function profile(){let r=await db.from("profiles").select("*").eq("id",S.u.id).maybeSingle();if(r.error)return msg(r.error.message);if(r.data?.company_id){let c=await db.from("companies").select("*").eq("id",r.data.company_id).single();if(!c.error)S.c=c.data}}
async function load(){await profile();if(!S.c)return;let id=S.c.id;let [a,p,ct,e]=await Promise.all([db.from("accounts").select("*").eq("company_id",id).order("code"),db.from("projects").select("*").eq("company_id",id).order("created_at",{ascending:false}),db.from("contacts").select("*").eq("company_id",id).order("name"),db.from("journal_entries").select("*").eq("company_id",id).order("entry_date",{ascending:false}).limit(10)]);if(a.error||p.error||ct.error||e.error)return alert((a.error||p.error||ct.error||e.error).message);S.a=a.data||[];S.p=p.data||[];S.ct=ct.data||[];render();dashboard(e.data||[])}
function render(){ $("accountsTable").innerHTML="<table><tr><th>Code</th><th>Name</th><th>Type</th></tr>"+S.a.map(x=>`<tr><td>${esc(x.code)}</td><td>${esc(x.name)}</td><td>${esc(x.account_type)}</td></tr>`).join("")+"</table>";$("contactsTable").innerHTML="<table><tr><th>Name</th><th>Type</th><th>Phone</th></tr>"+S.ct.map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.contact_type)}</td><td>${esc(x.phone)}</td></tr>`).join("")+"</table>";$("projectsTable").innerHTML="<table><tr><th>Code</th><th>Name</th><th>Budget</th></tr>"+S.p.map(x=>`<tr><td>${esc(x.code)}</td><td>${esc(x.name)}</td><td>${money(x.budget)}</td></tr>`).join("")+"</table>";lines()}
async function dashboard(es){let ids=es.map(x=>x.id),d=0,c=0;if(ids.length){let r=await db.from("journal_lines").select("debit,credit").in("journal_id",ids);(r.data||[]).forEach(x=>{d+=+x.debit;c+=+x.credit})}$("debit").textContent=money(d);$("credit").textContent=money(c);$("acount").textContent=S.a.length;$("pcount").textContent=S.p.length;$("recent").innerHTML=es.length?"<table><tr><th>Voucher</th><th>Date</th><th>Type</th></tr>"+es.map(x=>`<tr><td>${esc(x.voucher_no)}</td><td>${esc(x.entry_date)}</td><td>${esc(x.voucher_type)}</td></tr>`).join("")+"</table>":"No vouchers yet."}
$("companyForm").onsubmit=async e=>{e.preventDefault();let name=$("cname").value.trim();let r=await db.rpc("create_my_company",{p_name:name,p_currency:$("currency").value});if(r.error)return alert(r.error.message);S.c=r.data;alert("Company saved");await load()};
$("accountForm").onsubmit=async e=>{e.preventDefault();if(!S.c)return show("company");let r=await db.from("accounts").insert({company_id:S.c.id,code:$("acode").value,name:$("aname").value,account_type:$("atype").value});if(r.error)alert(r.error.message);else{e.target.reset();await load()}};
$("contactForm").onsubmit=async e=>{e.preventDefault();if(!S.c)return show("company");let r=await db.from("contacts").insert({company_id:S.c.id,name:$("ctname").value,contact_type:$("cttype").value,phone:$("phone").value,email:$("ctemail").value});if(r.error)alert(r.error.message);else{e.target.reset();await load()}};
$("projectForm").onsubmit=async e=>{e.preventDefault();if(!S.c)return show("company");let r=await db.from("projects").insert({company_id:S.c.id,code:$("pcode").value,name:$("pname").value,budget:+$("budget").value||0});if(r.error)alert(r.error.message);else{e.target.reset();await load()}};
function lines(){if(!$("lines").children.length){addLine();addLine()};document.querySelectorAll(".la").forEach(s=>s.innerHTML=S.a.map(a=>`<option value="${a.id}">${esc(a.code)} - ${esc(a.name)}</option>`).join(""))}
function addLine(){let d=document.createElement("div");d.className="grid";d.innerHTML='<select class="la"></select><input class="ld" placeholder="Description"><input class="db" type="number" min="0" step=".01" value="0"><input class="cr" type="number" min="0" step=".01" value="0">';$("lines").appendChild(d);lines();d.querySelectorAll("input").forEach(x=>x.oninput=totals);totals()}function totals(){let d=0,c=0;document.querySelectorAll(".db").forEach(x=>d+=+x.value);document.querySelectorAll(".cr").forEach(x=>c+=+x.value);$("td").textContent=d.toFixed(2);$("tc").textContent=c.toFixed(2)}
$("addLine").onclick=addLine;$("journalForm").onsubmit=async e=>{e.preventDefault();if(!S.c)return show("company");let ls=[...document.querySelectorAll("#lines .grid")].map(r=>({account_id:r.querySelector(".la").value,description:r.querySelector(".ld").value,debit:+r.querySelector(".db").value,credit:+r.querySelector(".cr").value})).filter(x=>x.debit||x.credit),d=ls.reduce((s,x)=>s+x.debit,0),c=ls.reduce((s,x)=>s+x.credit,0);if(!ls.length||Math.abs(d-c)>.005)return $("jmsg").textContent="Debit and Credit must be equal.";let e1=await db.from("journal_entries").insert({company_id:S.c.id,voucher_no:$("vno").value,voucher_type:$("vtype").value,entry_date:$("vdate").value,narration:$("narr").value,created_by:S.u.id}).select().single();if(e1.error)return alert(e1.error.message);let l=await db.from("journal_lines").insert(ls.map(x=>({...x,journal_id:e1.data.id})));if(l.error)return alert(l.error.message);$("jmsg").textContent="Voucher saved";e.target.reset();$("vdate").value=new Date().toISOString().slice(0,10);$("lines").innerHTML="";addLine();addLine();await load()};
$("refresh").onclick=report;async function report(){if(!S.c)return;let es=(await db.from("journal_entries").select("id").eq("company_id",S.c.id)).data||[],ids=es.map(x=>x.id);if(!ids.length)return $("report").textContent="No transactions yet.";let r=await db.from("journal_lines").select("account_id,debit,credit").in("journal_id",ids),m={};(r.data||[]).forEach(x=>{m[x.account_id]??={d:0,c:0};m[x.account_id].d+=+x.debit;m[x.account_id].c+=+x.credit});$("report").innerHTML="<table><tr><th>Account</th><th>Debit</th><th>Credit</th><th>Balance</th></tr>"+Object.entries(m).map(([id,v])=>{let a=S.a.find(x=>x.id===id);return `<tr><td>${a?esc(a.code+" - "+a.name):id}</td><td>${money(v.d)}</td><td>${money(v.c)}</td><td>${money(v.d-v.c)}</td></tr>`}).join("")+"</table>"}
db.auth.onAuthStateChange((_e,s)=>s&&enter(s.user));(async()=>{let r=await db.auth.getSession();if(r.data.session)enter(r.data.session.user)})();$("vdate").value=new Date().toISOString().slice(0,10);